language: c++

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
#   - os: osx
#     osx_image: xcode7.2

# check environment (copied from libgit2sharp)
before_install:
- date -u
- uname -a
#- sudo apt-get update -qq

# TODO: could move script to separate file
# Not running unit tests at the moment, so turn off testing, which will
# hopefully make OS X builds a bit faster
script:
  - cd bin
  - cmake -DDOWNLOAD_TOOLKITS:BOOL=OFF -DBUILD_TESTING:BOOL=OFF ../Superbuild
  - make -j4 1> /dev/null
#  make SCIRunTestData_external
#  && make test

notifications:
  slack: sciinstitute:lZnpQQXNd4Io5iGDPQDpJmI1
